commented out the lines that deal with mounting toplevel.

diff --git a/justso b/justso
--- a/justso
+++ b/justso
@@ -13,7 +13,7 @@ LATEST=""
 getLatest() {
     PROFILE=$1
 
-    mount -o "$MNT_OPTS" "$BTRFS_DEVICE" "$BTRFS_MOUNT"
+    # mount -o "$MNT_OPTS" "$BTRFS_DEVICE" "$BTRFS_MOUNT"
 
     if dirs=("$BTRFS_MOUNT"/@snapshots/"$PROFILE"/*/) && [[ -d ${dirs[0]} ]]; then
         LATEST=$(stat -c '%y %n' "$BTRFS_MOUNT"/@snapshots/"$PROFILE"/* | sort -n -r | head -n 1 | cut -f 4 -d " ")
@@ -32,10 +32,10 @@ back() {
         btrfs subvolume delete -c "$BTRFS_MOUNT"/@"$PROFILE"
         btrfs subvolume snapshot "$LATEST" "$BTRFS_MOUNT"/@"$PROFILE"
         mount "$HOME_FOLDER"
-        umount "$BTRFS_MOUNT"
+        # umount "$BTRFS_MOUNT"
     else
         echo "No snapshots exist for '$PROFILE'"
-        umount "$BTRFS_MOUNT"
+        # umount "$BTRFS_MOUNT"
         exit 2
     fi
 }
@@ -58,7 +58,7 @@ make() { # create a new profile revertable profile
     passwd "$PROFILE"
 
     # mount toplevel
-    mount -o "$MNT_OPTS" "$BTRFS_DEVICE" "$BTRFS_MOUNT"
+    # mount -o "$MNT_OPTS" "$BTRFS_DEVICE" "$BTRFS_MOUNT"
 
     # create subvolume
     btrfs subvolume create "${BTRFS_MOUNT}/@${PROFILE}"
@@ -95,7 +95,7 @@ make() { # create a new profile revertable profile
     btrfs subvolume snapshot -r "$HOME_FOLDER" "${SNAPS}/${PROFILE}/${PROFILE}-${NOW}"
 
     # unmount toplevel
-    umount "$BTRFS_MOUNT"
+    # umount "$BTRFS_MOUNT"
 
 }
 
@@ -115,9 +115,9 @@ init() { #C reates environment for justso
     else
         echo "Folder exists at /root/toplevel"
     fi
-    # Attempting to mount root volume at /root/toplevel
+    # Verify toplevel is mounted at /root/toplevel
     if grep -q 'root/toplevel\s' /etc/fstab && grep -q 'root/toplevel\s' /etc/mtab; then
-        echo "/root/toplevel is already mounted"
+        echo "/root/toplevel is mounted"
     else
         (mount /root/toplevel && echo "Mounted /root/toplevel") || "Failed to mount /root/toplevel"
     fi
@@ -135,11 +135,11 @@ init() { #C reates environment for justso
 
     # Unmount /root/toplevel
 
-    if umount "$BTRFS_MOUNT"; then
-        echo "/root/toplevel unmounted successfully!"
-    else
-        echo "Problem unmounting /root/toplevel: Error $?"
-    fi
+    # if umount "$BTRFS_MOUNT"; then
+    #     echo "/root/toplevel unmounted successfully!"
+    # else
+    #     echo "Problem unmounting /root/toplevel: Error $?"
+    # fi
 
 }
 
@@ -150,9 +150,9 @@ pin() { #Creates a new snapshot of a profile
     local NOW
     NOW=$(date --iso-8601=seconds)
 
-    mount "$BTRFS_DEVICE" "$BTRFS_MOUNT"
+    # mount "$BTRFS_DEVICE" "$BTRFS_MOUNT"
     btrfs subvolume snapshot -r "$HOME_FOLDER" "${SNAPS}/${PROFILE}/${PROFILE}-${NOW}"
-    umount "$BTRFS_MOUNT"
+    # umount "$BTRFS_MOUNT"
 }
 
 unpin() { #Removes the latest n snapshots defaults to 1
