complete working init function

diff --git a/justso b/justso
--- a/justso
+++ b/justso
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-#Global Variables
+# Global Variables
 
 BTRFS_MOUNT=/root/toplevel
 SNAPS="$BTRFS_MOUNT"/@snapshots
 MNT_OPTS="rw,noatime,compress=zstd:1,space_cache=v2"
 
-#Functions
+# Functions
 
 back() {
     local PROFILE="$1"
@@ -30,82 +30,82 @@ back() {
     fi
 }
 
-make() { #create a new profile revertable profile
+make() { # create a new profile revertable profile
     local PROFILE="$1"
     local HOME_FOLDER=/home/"$PROFILE"
     local NOW
     NOW=$(date --iso-8601=seconds)
 
-    #If fstab backup folder doesn't exist, create it
+    # If fstab backup folder doesn't exist, create it
     if [ ! -d /root/fstab_backup ]; then
         mkdir /root/fstab_backup
     fi
 
-    #create user w/o home folder (will be created manually later)
+    # create user w/o home folder (will be created manually later)
     useradd -M -s /bin/bash "$PROFILE"
 
-    #set password
+    # set password
     passwd "$PROFILE"
 
-    #mount toplevel
+    # mount toplevel
     mount -o "$MNT_OPTS" /dev/vda3 "$BTRFS_MOUNT"
 
-    #create subvolume
+    # create subvolume
     btrfs subvolume create "${BTRFS_MOUNT}/@${PROFILE}"
 
-    #create entry in fstab
+    # create entry in fstab
     ROOT_LINE=$(grep subvol=@" " /etc/fstab)
     TEMP_ENTRY=${ROOT_LINE//subvol=@/subvol=@"$PROFILE"}
     NEW_ENTRY=${TEMP_ENTRY/\//\/home/"$PROFILE"}
     echo "$NEW_ENTRY"
 
-    #Create a backup of fstab
+    # Create a backup of fstab
     cp -a /etc/fstab /root/fstab_backup/fstab."${NOW}".bak
 
-    #Insert "NEW_ENTRY" into fstab
+    # Insert "NEW_ENTRY" into fstab
     sed --in-place=.bak "/^.*\/home.*/a $NEW_ENTRY" /etc/fstab
 
-    #make home folder
+    # make home folder
     mkdir "$HOME_FOLDER"
 
-    #mount btrfs subvolume and set ownership
+    # mount btrfs subvolume and set ownership
     mount "$HOME_FOLDER"
     chown "$PROFILE":"$PROFILE" /home/"$PROFILE"
 
-    #Propulate the home folder with default files and folders
+    # Propulate the home folder with default files and folders
     su -c "cp -r /etc/skel/. /home/$PROFILE" "$PROFILE"
     su -c xdg-user-dirs-update "$PROFILE"
 
-    #create folder in /.snapshots
+    # create folder in /.snapshots
     if [ ! -d "${SNAPS}/${PROFILE}" ]; then
         mkdir "${SNAPS}/${PROFILE}"
     fi
 
-    #take initial snapshot
+    # take initial snapshot
     btrfs subvolume snapshot -r "$HOME_FOLDER" "${SNAPS}/${PROFILE}/${PROFILE}-${NOW}"
 
-    #unmount toplevel
+    # unmount toplevel
     umount "$BTRFS_MOUNT"
 
 }
 
-init() { #Creates environment for justso
+init() { #C reates environment for justso
     echo "Hello world, I'm init"
-    #Checking for folder at /root/fstab_backup
+    # Checking for folder at /root/fstab_backup
     if [ ! -d /root/fstab_backup ]; then
         mkdir /root/fstab_backup
         echo "Created folder at /root/fstab_backup"
     else
         echo "Folder exists at /root/fstab_backup"
     fi
-    #Checking for folder at /root/toplevel
+    # Checking for folder at /root/toplevel
     if [ ! -d /root/toplevel ]; then
         mkdir /root/toplevel
         echo "Created folder at /root/toplevel"
     else
         echo "Folder exists at /root/toplevel"
     fi
-    #Attempting to mount root volume at /root/toplevel
+    # Attempting to mount root volume at /root/toplevel
     if grep -q 'root/toplevel\s' /etc/fstab && grep -q 'root/toplevel\s' /etc/mtab; then
         echo "/root/toplevel is already mounted"
     else
@@ -113,15 +113,23 @@ init() { #Creates environment for justso
     fi
 
     #Checking for the existence of @snapshots subvolume
-    # if btrfs subvolume show /root/toplevel/@snapshots >/dev/null 2>&1; then
-    #     echo "@snapshots subvolume exists"
-    # else
-    #     if btrfs subvolume create /root/toplevel/@snapshots >/dev/null 2>&1; then
-    #         echo "Successfully created @snapshots subvolume"
-    #     else
-    #         "There was an error creating the @snapshots subvolume: Error $?"
-    #     fi
-    # fi
+    if btrfs subvolume show /root/toplevel/@snapshots >/dev/null 2>&1; then
+        echo "@snapshots subvolume exists"
+    else
+        if btrfs subvolume create /root/toplevel/@snapshots >/dev/null 2>&1; then
+            echo "Successfully created @snapshots subvolume"
+        else
+            "There was an error creating the @snapshots subvolume: Error $?"
+        fi
+    fi
+
+    # Unmount /root/toplevel
+
+    if umount "$BTRFS_MOUNT"; then
+        echo "/root/toplevel unmounted successfully!"
+    else
+        echo "Problem unmounting /root/toplevel: Error $?"
+    fi
 
 }
 
